version: '3.9'
services:
  apache1:
    image: httpd:latest
    container_name: apacheDari1
    ports:
      - '8081:80'
    volumes:
      - ./index1.html:/usr/local/apache2/htdocs/index.html
      - ./public:/usr/local/apache2/htdocs/public

  client:
    image: nginx:latest
    container_name: nginx2
    ports:
    - '80:80'
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: BDDari
      MYSQL_USER: Dari
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
 
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ELtiempoDari
    working_dir: /var/www/html
    volumes:
      - ./ELtiempoDari:/var/www/html
    ports:
      - "8082:8000"  # Mapea el puerto 8082 del host al puerto 8000 del contenedor
    depends_on:
      - mysql

  laravel-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-back
    working_dir: /var/www/html
    volumes:
     - ./LaravelInsert:/var/www/html
    ports:
     - "8083:8000"  # Mapea el puerto 8083 del host al puerto 8000 del contenedor
    depends_on:
     - mysql
     - laravel-app
    command: php artisan schedule:work

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql